#!/bin/bash
#creates a list of switches
declare -A SWITCH
SWITCH='name1'
SWITCH='name2'
SWITCH='name3'
SWITCH='osf'
SWITCH='crt'
#the following file contains a list of servers (either with FQDN or IP address), connected to a switch
IPLIST="/data/tftpboot/ping/$SWITCH"
#runs 100 pings and returns "ok" or "fail" for each IP address it pings
for i in {1..100}
do
echo""
echo "---------Starting $i ping round-------"
echo""
for ip in $(cat $IPLIST)

do
    ping $ip -c 1 &> /dev/null
    if [ $? -ne 0 ]; then

        echo $ip FAIL;

        else

        echo $ip OK;

    fi

done
echo""
echo "---------End of $i round-------"
sleep 2
done
